V=["showing teeth, smiling, and clenching fists",
"smiling brightly with heart shape in the eyes",
"getting on the knees with the head slightly bowed",
"Raising eyebrows and opening mouth slightly with a faint smile",
"Shaking head from side to side",
"Sighing and punching in the chest",
"Knitting brows and opening mouth slightly to one side",
"Raising fist, and frowning with mouth closed",
"opening eyes wide and putting hands on chin",
"raising the corners of the mouth slightly with eyes closed",
"nodding head up and down",
"biting nails and shaking",
"opening mouth slightly with squinting eyes",
"having dark circles under eyes with blank expression",
"putting chin on hand with narrowed eyes",
"furrowing eyebrows and raising only one corner of the mouth",
"putting hands on chest and with twinkling eyes",
"laughing with mouth wide open",
"closing eyes and putting hands together",
"trembling and sweating",
"opening the mouth wide open up and down with raised eyebrows and pupils and eyes widen",
"shedding tears, dropping the corners of mouth with wrinkles on the forehead",
"frowning with cheeks swollen as if it's about to vomit",
"roaring with mouth wide open",
"frowning, and opening mouth wide to the side to show teeth",
"looking sideways with squinting eyes in a stiff posture",
"raising eyebrows, opening eyes wide with a little tears, and opening mouth",
"putting hands together next to chin, opening eyes wide and mouth small",
"ends of eyebrows going down and opening mouth in the shape of a triangle as if it's crying",
"raising eyebrows, opening eyes and mouth wide open",
"frowning slightly, saying something, and pointing forward with finger",
"frowning strongly, drooping the corners of mouth a lot, and showing lower teeth"]
